.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X.
.P
dwm "orders" windows based on recency and primacy, while dwm layouts may
change, the most recent "master" window is shown in the most prominent
position. There are bindings for cycling through and promoting windows to the
master position.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
Each screen contains a small status bar which displays all available tags, the
layout, the title of the focused window, and the text read from the root window
name property, if the screen is focused. A floating window is indicated with an
empty square and a maximized floating window is indicated with a filled square
before the windows title.  The selected tags are indicated with a different
color. The tags of the focused window are indicated with a filled square in the
top left corner.  The tags which are applied to one or more windows are
indicated with an empty square in the top left corner.
.P
dwm draws a small border around windows to indicate the focus state.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.SS Status bar
.TP
.B X root window name
is read and displayed in the status text area. It can be set with the
.BR xsetroot (1)
command.
.TP
.B Left click
click on a tag label to display all windows with that tag, click on the layout
label toggles between tiled and floating layout.
.TP
.B Right click
click on a tag label adds/removes all windows with that tag to/from the view.
.TP
.B Super\-Left click
click on a tag label applies that tag to the focused window.
.TP
.B Super\-Right click
click on a tag label adds/removes that tag to/from the focused window.
.SS Keyboard commands
.TP
.B Super\-q
Close focused window.
.TP
.B Super\-w
Start browser,
.BR Firefox.
.TP
.B Super\-e
Start graphical file manager,
.BR Dolphin.
.TP
.B Super\-r
Spawn
.BR dmenu (1)
for launching other programs.
.TP
.B Super\-t
Start terminal,
.BR st (1)
.
.TP
.B Super\-Shift\-t
Toggle scratch terminal,
.BR st (1)
.
.TP
.B Super\-y
Toggle smart gaps.
.TP
.B Super\-u/i
Decrease/increase number of windows in master area.
.TP
.B Super\-i
Increase number of windows in master area.
.TP
.B Super\-o
Start terminal file manager,
.BR lf (1)
.
.TP
.B Super\-p
Start browser,
.BR Firefox
in private window.
.TP
.B Super\-Shift\-p
Toggle mpd playback.
.TP
.B Super\-minus/equal
Decrease/increase volume by 5.
.TP
.B Super\-left/right bracket
Cycle through layouts.
.TP
.B Super\-a
Toggle gaps.
.TP
.B Super\-Shift\-a
Set gaps to default.
.TP
.B Super\-s
Toggle sticky for focused window.
.TP
.B Super\-d
Toggle scratch calculator.
.TP
.B Super\-f
Toggle fullscreen window.
.TP
.B Super\-g
Toggle previously focused tag.
.TP
.B Super\-h/l
Decrease/increase master area size.
.TP
.B Super\-j/k
Focus next/previous window.
.TP
.B Super\-Shift\-h
Start the man page.
.TP
.B Super\-Shift\-l
Lock the computer.
.TP
.B Super\-Shift\-j/k
Move selected window up/down in stack. I haven't done this, I need to do it.
.TP
.B Super\-semicolon/apostrophe
Focus left/right monitor.
.TP
.B Super\-Shift\-semicolon/apostrophe
Move current window to the left/right monitor.
.TP
.B Super\-z/x
Decrease/increase gaps between windows.
.TP
.B Super\-c
Cycle focused window to/from master area.
.TP
.B Super\-v
Toggle focused window between tiled and floating layout.
.TP
.B Super\-Shift\-v
Start clipmenu.
.TP
.B Super\-b
Toggles bar on and off.
.TP
.B Super\-n
Start
.BR nvim (1)
.
.TP
.B Super\-Shift\-n
Start
.BR weechat (1)
.
.TP
.B Super\-m
Start
.BR ncmpcpp (1)
.
.TP
.B Super\-Shift\-m
Mute audio.
.TP
.B Super\-comma/period
Previous/next song on mpd.
.TP
.B Super\-slash
View all windows with any tag.
.TP
.B Super\-Shift\-slash
Apply all tags to focused window.
.TP
.B Alt\-Tab
Cycle between windows.
.TP
.B Super\-Space
Select a directory to open in a terminal, file manager, editor, or file browser.
.TP
.B Printscreen
Take a screenshot of the selected area (also copies to your clipboard).
.TP
.B Ctrl\-Printscreen
Take a screenshot of the focused window (also copies to your clipboard).
.TP
.B Super\-Printscreen
Take a screenshot of the current screen (also copies to your clipboard).
.TP
.B Alt\-Printscreen
Take a screenshot of the entire screen - multiple monitors (also copies to your clipboard).
.TP
.B Super\-F1
Start the man page.
.TP
.B Super\-F2
Toggle audio devices.
.TP
.B Super\-F3
Start cava.
.TP
.B Super\-F4
Start pulsemixer.
.TP
.B Super\-F5
Refresh appearance by running xrdb.
.TP
.B Super\-F6
Toggle VPN.
.TP
.B Super\-Backspace
Refresh/quit/reboot/shutdown etc.
.TP
.B Super\-Shift\-Backspace
Refresh/quit/reboot/shutdown etc with a delay.
.TP
.B Super\-[1..8]
View all windows with tag.
.TP
.B Super\-Tab
View all windows with next tag.
.TP
.B Super\-Shift\-Tab
View all windows with previous tag.
.TP
.B Super\-Shift\-[1..8]
Apply tag to focused window.
.TP
.B Super\-Control\-[1..8]
Add/remove all windows with tag to/from the view.
.TP
.B Super\-Control\-Shift\-[1..8]
Add/remove tag to/from focused window.
.SS Mouse commands
.TP
.B Super\-Left click
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B Super\-Middle click
Toggles focused window between floating and tiled state.
.TP
.B Super\-Right click
Resize focused window while dragging. Tiled windows will be toggled to the floating state.
.SH CUSTOMIZATION
dwm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SH BUGS
Send all bug reports with a patch to hackers@suckless.org.
